myblog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(10), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    is_delete = db.Column(db.Boolean(), default=0)
    create_time = db.Column(db.DateTime, default=datetime.now())
    # user_info = db.Column(db.Integer, db.ForeignKey('user_info.id'))

    __tablename__='user'

    def save(self):
        db.session.add(self)
        db.session.commit()


class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name = db.Column(db.String(10), unique=True, nullable=False)
    arts = db.relationship('Article', backref='tp')

    __tablename__ = 'art_type'


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), unique=True, nullable=False)
    desc = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now())
    type = db.Column(db.Integer, db.ForeignKey('art_type.id'))


class UserInfo(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    account = db.Column(db.String(30), unique=True, nullable=False)
    tel = db.Column(db.String(20), nullable=False)
    mail = db.Column(db.String(30), nullable=False)
    is_logout = db.Column(db.Boolean, nullable=False)
    # u_id = db.relationship('User', backref='ui')

myblog/back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from back.models import User, Article, ArticleType, db
from utils.functions import is_login

back_blue = Blueprint('back',__name__)


@back_blue.route('/index/')
@is_login
def index():
    return render_template('back/index.html')


@back_blue.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if username and password and password2:
            # 判断该账号是否被注册过
            user = User.query.filter(User.username == username).first()
            if user:
                error = '该账号已经注册，请更换账号'
                return render_template('back/register.html', error=error)
            else:
                if password2 == password:
                    # 保存数据
                    user = User()
                    user.username = username
                    user.password = generate_password_hash(password)
                    user.save()
                    return redirect(url_for('back.login'))

                else:
                    # 密码错误
                    error = '两次密码不一致'
                    return render_template('back/register.html', error=error)

        else:
            error = '请填写完整的信息'
            return render_template('back/register.html', error=error)


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')
    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '该账号不存在，请去注册'
                return render_template('back/login.html', error=error)
            if not check_password_hash(user.password, password):
                error = '密码错误，请输入正确的密码'
                return render_template('back/login.html', error=error)
            # 账号和密码匹配正确，跳转到首页
            session['user_id'] = user.id
            return redirect(url_for('back.index'))
        else:
            error = '请填写完整的登录信息'
            return render_template('back/login.html', error=error)


@back_blue.route('/logout/',methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))


@back_blue.route('/a_type/',methods=['GET','POST'])
@is_login
def a_type():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/category_list.html', types=types)


@back_blue.route('/add_type/',methods=['GET', 'POST'])
@is_login
def add_type():
    if request.method == 'GET':
        return render_template('back/category_add.html')
    if request.method == 'POST':
        atype = request.form.get('atype')
        if atype:
            # 保存分类信息
            art_type = ArticleType()
            art_type.t_name = atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.a_type'))
        else:
            error = '请填写分类信息'
            return render_template('back/category_add.html', error=error)


@back_blue.route('/del_type/<int:id>/', methods=['GET'])
@is_login
def del_type(id):
    # 删除分类
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))


@back_blue.route('/article_list/', methods=['GET'])
@is_login
def article_list():
    page = int(request.args.get('page', 1))

    # 每一页的条数多少，默认为10条
    per_page = int(request.args.get('per_page', 10))

    # 查询当前第几个的多少条数据
    paginate = Article.query.order_by('id').paginate(page, per_page, error_out=False)
    articles = paginate.items
    return render_template('back/article_list.html', articles=articles, paginate=paginate)


@back_blue.route('/article_add/', methods=['GET', 'POST'])
@is_login
def article_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/article_detail.html', types=types)

    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            types = ArticleType.query.all()
            error = '请填写完整的文章信息'
            return render_template('back/article_detail.html', error=error, types=types)


@back_blue.route('/article_change/<int:id>/', methods=['GET', 'POST'])
@is_login
def article_change(id):
    if request.method == 'GET':
        types = ArticleType.query.all()
        article = Article.query.get(id)
        return render_template('back/article_change.html', article=article, types=types)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.commit()
            return redirect(url_for('back.article_list'))
        else:
            article = Article.query.get(id)
            types = ArticleType.query.all()
            error = '请修改文章信息'
            return render_template('back/article_change.html', error=error, article=article, types=types)


@back_blue.route('/del_article/<int:id>/', methods=['GET'])
@is_login
def del_article(id):
    if request.method == 'GET':
        article = Article.query.get(id)
        db.session.delete(article)
        db.session.commit()
        return redirect(url_for('back.article_list'))


@back_blue.route('/user_list/', methods=['GET'])
@is_login
def user_list():
    if request.method == 'GET':
        return render_template('back/user_list.html')
    if request.method == 'POST':
        pass

myblog/web/views.py
from flask import Blueprint, render_template, request, redirect, url_for, g
from sqlalchemy import and_, or_

from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    page = int(request.args.get('page', 1))

    # 每一页的条数多少，默认为10条
    per_page = int(request.args.get('per_page', 10))

    # 查询当前第几个的多少条数据
    paginate = Article.query.order_by('id').paginate(page, per_page, error_out=False)

    articles = paginate.items
    types = ArticleType.query.all()
    return render_template('web/index.html', articles=articles, types=types, paginate=paginate)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    n_article = Article.query.get(id-1)
    return render_template('web/info.html', article=article, n_article=n_article)


@web_blue.route('/category/<int:id>/')
def category(id):
    types = ArticleType.query.all()
    articles = Article.query.filter(Article.type == id).all()
    if not articles:
        error = '未找到相关文章'
        return render_template('web/category.html', articles=articles, types=types, error=error)
    else:
        return render_template('web/category.html', articles=articles, types=types)


@web_blue.route('/search/', methods=['POST'])
def search():
    content = request.form.get('keyboard')
    articles = Article.query.filter(or_(Article.title.contains(content),
                                    Article.content.contains(content))
                                    ).all()
    if request.method == 'POST':
        if not articles:
            error = '没有找到符合条件的文章'
            paginate = {}
            return render_template('web/index.html', error=error, paginate=paginate)
        else:
            paginate = {}
            return render_template('web/index.html', articles=articles, paginate=paginate)


@web_blue.route('/about/')
def about():
    return render_template('web/about.html')


@web_blue.route('/share/')
def share():
    page = int(request.args.get('page', 1))

    # 每一页的条数多少，默认为10条
    per_page = int(request.args.get('per_page', 8))

    # 查询当前第几个的多少条数据
    paginate = Article.query.order_by('id').paginate(page, per_page, error_out=False)

    articles = paginate.items
    return render_template('web/share.html', articles=articles)


@web_blue.route('/content/')
def content():
    article = Article.query.get(22)
    n_article = Article.query.get(21)
    return render_template('web/info.html', article=article, n_article=n_article)

    # return render_template('web/info.html',id=23)


# @web_blue.before_request
# def art_info():
#     types = ArticleType.query.all()
#     articles = Article.query.filter(Article.type == id).all()
#     g.types = types
#     g.articles = articles
# 狗子函数

myblog/templates/back/article_change.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章详情</h2>
            <a class="fr top_rt_btn" href="/back/article_list/">返回文章列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {{ error }}
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value="{{ article.title }}" class="textbox textbox_295" placeholder=""/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value="{{ article.desc }}"  class="textbox" placeholder=""/>

                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章分类：</span>
                        <select class="select" name="category">
                                {% for type in types %}
                                <option value="{{ type.id }}">{{ type.t_name }}</option>
                                {% endfor %}
                        </select>

                    </li>
                    <!--<li>-->
                        <!--<span class="item_name" style="width:120px;">文章详情：</span>-->
                        <!--<input type="text" name="content" value="{{ article.content }}"  class="textbox textbox_295" placeholder=""/>-->

                    <!--</li>-->
                    <li>
                        <span class="item_name" style="width:120px;">文章详情：</span>

                        <textarea id="editor_id" name="content" style="width:700px;height:300px;">{{ article.content }}</textarea>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

myblog/templates/back/article_detail.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章添加
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章详情</h2>
            <a class="fr top_rt_btn" href="/back/article_list/">返回文章列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {{ error }}
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value="" class="textbox textbox_295" placeholder=""/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value=""  class="textbox" placeholder=""/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章分类：</span>
                        <select class="select" name="category">
                                {% for type in types %}
                                <option value="{{ type.id }}">{{ type.t_name }}</option>
                                {% endfor %}
                        </select>

                    </li>
                    <!--<li>-->
                        <!--<span class="item_name" style="width:120px;">文章详情：</span>-->
                        <!--<input type="text" name="content" value=""  class="textbox textbox_295" placeholder=""/>-->
                        <!---->
                    <!--</li>-->
                    <li>
                        <span class="item_name" style="width:120px;">文章详情：</span>

                        <textarea id="editor_id" name="content" style="width:700px;height:300px;">
                             &lt;strong&gt;HTML内容&lt;/strong&gt;
                        </textarea>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

myblog/templates/back/article_list.html
{% extends 'back/base_main.html' %}
{% block title %}
    文章列表页面
{% endblock %}


{% block content %}
<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章列表</h2>
            <a href="{{ url_for('back.article_add') }}" class="fr top_rt_btn add_icon">添加文章</a>
        </div>
        <table class="table">
            <tr>
                <th>文章标题</th>
                <th>文章分类</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
                {{ error }}
            {% for article in articles %}
                <tr>
                        <td class="center">{{ article.title }}</td>
                        <td class="center">{{ article.tp.t_name }}</td>
                        <td class="center">{{ article.create_time }}</td>

                    <td class="center">
                        <a href="{{ url_for('back.article_change', id=article.id ) }}" title="编辑" class="link_icon">&#101;</a>
                        <a href="{{ url_for('back.del_article',id = article.id) }}"  title="删除" class="link_icon">&#100;</a>
                    </td>

                </tr>
            {% endfor %}

        </table>
        <aside class="paging">
            <a>当前{{ paginate.page }}页</a>

            {% if paginate.has_prev %}
            <a href="/back/article_list/?page={{ paginate.prev_num }}">上一页</a>
            {% endif %}

            {% for i in range(1,paginate.pages+1) %}
                <a href="/back/article_list/?page={{ i }}"> {{ i }}</a>
            {% endfor %}

            {% if paginate.has_next %}
            <a href="/back/article_list/?page={{ paginate.next_num }}">下一页</a>
            {% endif %}
            <a href="/back/article_list/?page={{ paginate.pages }}">最后一页</a>

        </aside>
    </div>
</section>
{% endblock %}

myblog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

    {% block meta %}
    {% endblock %}

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
<div></div>
    {% block header %}
    {% endblock %}

    {% block aside %}

    {% endblock %}

    {% block content %}

    {% endblock %}

</body>
</html>

myblog/templates/back/base_main.html
{% extends 'back/base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
{% endblock%}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock%}

{% block header %}
    <header>
        <h1><img src="/static/back/images/admin_logo.png"/></h1>
        <ul class="rt_nav">
            <li><a href="{{ url_for('web.index') }}" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="#" class="set_icon">账号设置</a></li>
            <li><a href="{{ url_for('back.logout') }}" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock%}

{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">博客后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>文章管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="{{ url_for('back.a_type') }}">文章分类</a></dd>
                    <dd><a href="{{ url_for('back.article_list') }}">文章列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="{{ url_for('back.user_list')}}">用户信息</a></dd>
                </dl>
            </li>
        </ul>
    </aside>
{% endblock %}

{% block content %}

{% endblock %}

myblog/templates/back/category_add.html
{% extends 'back/base_main.html' %}
{% block title %}
    添加分类
{% endblock %}
{% block content %}
<section class="rt_wrap mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类</h2>
            <a class="fr top_rt_btn" href="goods_category_list.html">返回文章分类列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">分类名称：</span>
                        <input name="atype" type="text" name="atype">
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn" value="确认添加" />
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

myblog/templates/back/category_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章分类
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">分类列表</h2>
                <a href="{{ url_for('back.add_type') }}" class="fr top_rt_btn add_icon">添加文章分类</a>
            </div>
            <table class="table">
                <tr>
                    <th>分类名</th>
                    <th>操作</th>
                </tr>
                {% for type in types %}
                    <tr>
                        <td class="center">
                           {{ type.t_name }}
                        </td>
                        <td class="center">
                            <a href="{{ url_for('back.del_type',id=type.id) }}" title="删除" class="link_icon">&#101;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>
{% endblock %}

myblog/templates/back/goods_desc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
         <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_list.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>



<section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='QuPi2QUuEhlKchGijsQULGJKUZO6bOJacZPtDzGnIfWv89lLhtnbVM2EVRxtAXCJ' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>



</body>
</html>

myblog/templates/back/index.html
{% extends 'back/base_main.html' %}
{% block title %}
    后台管理系统--首页
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="/static/back/js/html5.js"></script>
    <script>
        (function($){
            $(window).load(function(){

                $("a[rel='load-content']").click(function(e){
                    e.preventDefault();
                    var url=$(this).attr("href");
                    $.get(url,function(data){
                        $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
                        //scroll-to appended content
                        $(".content").mCustomScrollbar("scrollTo","h2:last");
                    });
                });

                $(".content").delegate("a[href='top']","click",function(e){
                    e.preventDefault();
                    $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
                });

            });
        })(jQuery);
    </script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                博客管理后台
            </h1>
            <br>
            <p>商城管理采用flask开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>商城后台集中功能为：文章发布、用户管理等</p>
        </div>
    </section>
{% endblock %}

myblog/templates/back/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>

    <link rel="stylesheet" type="text/css" href="css/style.css">

    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_detail.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>




<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">订单列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>订单编号</th>
                <th>收件人</th>
                <th>联系电话</th>
                <th>收件人地址</th>
                <th>订单金额</th>
                <th>配送方式</th>
                <!--<th>操作</th>-->
            </tr>
            
                <tr>
                    <td class="center">Pg5Wq4GYKWge6fhMDiMI</td>
                    <td>小花</td>
                    <td>12887754321</td>
                    <td>
                        <address>四川省成都市</address>
                    </td>
                    <td class="center"><strong class="rmb_icon">1260.0</strong></td>
                    <td class="center">申通快递</td>
                    <!--<td class="center">-->
                        <!--<a href="#" title="查看订单" class="link_icon" target="_blank">&#118;</a>-->
                    <!--</td>-->
                </tr>
        </table>
        <aside class="paging">
            <a>当前1页</a>
            <a href="">第一页</a>
            
                <a href=""> 1 </a>
                <a href=""> 2 </a>
                <a href=""> 3 </a>
                <a href=""> 4 </a>
            
            <a href="">最后一页</a>
        </aside>
    </div>
</section>



</body>
</html>