myblog/web/views.py
from flask import Blueprint, render_template, request, redirect, url_for, g
from sqlalchemy import and_, or_

from back.models import Article, ArticleType

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    page = int(request.args.get('page', 1))

    # 每一页的条数多少，默认为10条
    per_page = int(request.args.get('per_page', 10))

    # 查询当前第几个的多少条数据
    paginate = Article.query.order_by('id').paginate(page, per_page, error_out=False)

    articles = paginate.items
    types = ArticleType.query.all()
    return render_template('web/index.html', articles=articles, types=types, paginate=paginate)


@web_blue.route('/info/<int:id>/')
def info(id):
    article = Article.query.get(id)
    n_article = Article.query.get(id-1)
    return render_template('web/info.html', article=article, n_article=n_article)


@web_blue.route('/category/<int:id>/')
def category(id):
    types = ArticleType.query.all()
    articles = Article.query.filter(Article.type == id).all()
    if not articles:
        error = '未找到相关文章'
        return render_template('web/category.html', articles=articles, types=types, error=error)
    else:
        return render_template('web/category.html', articles=articles, types=types)


@web_blue.route('/search/', methods=['POST'])
def search():
    content = request.form.get('keyboard')
    articles = Article.query.filter(or_(Article.title.contains(content),
                                    Article.content.contains(content))
                                    ).all()
    if request.method == 'POST':
        if not articles:
            error = '没有找到符合条件的文章'
            paginate = {}
            return render_template('web/index.html', error=error, paginate=paginate)
        else:
            paginate = {}
            return render_template('web/index.html', articles=articles, paginate=paginate)


@web_blue.route('/about/')
def about():
    return render_template('web/about.html')


@web_blue.route('/share/')
def share():
    page = int(request.args.get('page', 1))

    # 每一页的条数多少，默认为10条
    per_page = int(request.args.get('per_page', 8))

    # 查询当前第几个的多少条数据
    paginate = Article.query.order_by('id').paginate(page, per_page, error_out=False)

    articles = paginate.items
    return render_template('web/share.html', articles=articles)


@web_blue.route('/content/')
def content():
    article = Article.query.get(22)
    n_article = Article.query.get(21)
    return render_template('web/info.html', article=article, n_article=n_article)

    # return render_template('web/info.html',id=23)


# @web_blue.before_request
# def art_info():
#     types = ArticleType.query.all()
#     articles = Article.query.filter(Article.type == id).all()
#     g.types = types
#     g.articles = articles
# 狗子函数

myblog/templates/web/about.html
{% extends 'web/base_main.html' %}

{% block content %}

<main class="r_box">
     <div class="about">
      <p>杨青，女，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/web/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
                <img src="/static/web/images/1.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，280998807(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>域 名：www.yangqq.com 创建于2011年01月12日&nbsp;</p>
          <br />
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>
  
     </div>
  </main>
{% endblock %}

myblog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
        {% block meta %}
        {% endblock %}

        {% block css %}
        {% endblock %}

        {% block js %}
        {% endblock %}

</head>
<body>
    <h1></h1>
    {% block header %}
    {% endblock %}
    <article>
        <aside class="l_box">
            {% block about %}
            {% endblock %}

            {% block search %}
            {% endblock %}
        </aside>

        {% block content %}
        {% endblock %}


    </article>
    {% block bottom %}
    {% endblock %}
</body>
</html>

myblog/templates/web/base_main.html
{% extends 'web/base.html'%}

{% block title %}
    首页_郑晓卫个人博客 - 一个站在Python前端设计之路小白的个人博客网站
{% endblock %}

{% block meta %}
    <meta name="keywords" content="个人博客,郑晓卫个人博客,个人博客模板" />
    <meta name="description" content="郑晓卫个人博客，是一个站在web前端设计之路的小白程序员个人网站。" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
<style>

body{
    background: url(/static/web/images/15.jpg);
    background-size: cover;
}


</style>

{% endblock %}

{% block js %}
    <script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/web/js/comm.js"></script>
    <script src="/static/web/js/modernizr.js"></script>

{% endblock %}

{% block header %}
    <header class="header-navigation" id="header">
        <nav><div class="logo"><a href="{{ url_for('web.index') }}">郑晓卫个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
        <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
        <li><a href="{{ url_for('web.share') }}">我的相册</a></li>
        <!--<li><a href="">我的日记</a></li>-->
        <!--<li><a href="">留言</a></li>-->
        <li><a href="{{ url_for('web.content') }}">内容页</a></li>
        <li><a href="{{ url_for('web.about') }}">关于我</a></li>
        </ul>
        </nav>
    </header>
{% endblock %}

{% block about %}
    <div class="about_me">
        <h2>关于我</h2>
        <ul>
            <i><img src="/static/web/images/p1.jpg"></i>
            <p><b>郑晓卫</b> 男，一个90后草根男站长！17年入行。一直虚心学习python技术，一边工作一边积累经验，分享一些个人学习内容，以及学习心得。</p>
        </ul>
    </div>
{% endblock %}

{% block search %}
<div class="search">
    <form action="/web/search/" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
    </form>
</div>
{% endblock %}

{% block bottom %}
<footer>
  <p>Design by <a href="/" target="_blank">郑晓卫个人博客</a> <a href="/">陕ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

myblog/templates/web/base_main_second.html
{% extends 'web/base.html'%}
{% block title %}
    首页_郑晓卫个人博客 - 一个站在Python前端设计之路小白的个人博客网站
{% endblock %}

{% block meta %}
    <meta name="keywords" content="个人博客,郑晓卫个人博客,个人博客模板" />
    <meta name="description" content="郑晓卫个人博客，是一个站在web前端设计之路的小白程序员个人网站。" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
<style>

body{
    background: url(/static/web/images/15.jpg);
    background-size: cover;
}


</style>

{% endblock %}

{% block js %}
    <script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/web/js/comm.js"></script>
    <script src="/static/web/js/modernizr.js"></script>

{% endblock %}

{% block header %}
    <header class="header-navigation" id="header">
        <nav><div class="logo"><a href="/">郑晓卫个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
        <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
        <li><a href="">我的相册</a></li>
        <!--<li><a href="">我的日记</a></li>-->
        <!--<li><a href="">留言</a></li>-->
        <li><a href="info.html">内容页</a></li>
        <li><a href="{{ url_for('web.about') }}">关于我</a></li>
        </ul>
        </nav>
    </header>
{% endblock %}

{% block search %}
    <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
            <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
            <input name="show" value="title" type="hidden">
            <input name="tempid" value="1" type="hidden">
            <input name="tbname" value="news" type="hidden">
            <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
    </div>
    <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            <li><a href="/">学无止境（33）</a></li>
            <li><a href="/">日记（19）</a></li>
            <li><a href="/">慢生活（520）</a></li>
            <li><a href="/">美文欣赏（40）</a></li>
        </ul>
    </div>
    <div class="links">
        <h2>友情链接</h2>
        <ul>
            <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
        </ul>
    </div>
    <div class="guanzhu">
        <h2>关注我加微信</h2>
        <ul>
            <img src="/static/web/images/wx.jpg">
        </ul>
    </div>
{% endblock %}

{% block bottom %}
<footer>
  <p>Design by <a href="/" target="_blank">郑晓卫个人博客</a> <a href="/">陕ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
{% endblock %}

myblog/templates/web/category.html
{% extends 'web/base_main.html' %}

{% block search %}
    {{ super() }}
        <div class="fenlei">
            <h2>文章分类</h2>
            {% for type in types %}
            <ul>
                <li><a href="{{ url_for('web.category',id=type.id)}}">{{ type.t_name }}</a></li>
            </ul>
            {% endfor %}
        </div>
        <div class="links">
            <h2>友情链接</h2>
        </div>
        <div class="guanzhu">
        <h2>关注请加我微信</h2>
        <ul>
            <img src="/static/web/images/wx.jpg">
        </ul>
        </div>
{% endblock %}

{% block content %}
  <main class="r_box">
        {{ error }}
    {% for article in articles %}
        {% if article.id %10 == 0 %}
            <li><i><a href="/"><img src="/static/web/images/10.jpg"></a></i>
            <h3><a href="{{ url_for('web.info',id=article.id)}}">{{ article.title }}</a></h3>
            <p>{{ article.desc }}</p>
            </li>
        {% endif%}

        {% if article.id %10 != 0 %}
            <li><i><a href="/"><img src="/static/web/images/{{ article.id%10 }}.jpg"></a></i>
            <h3><a href="{{ url_for('web.info',id=article.id)}}">{{ article.title }}</a></h3>
            <p>{{ article.desc }}</p>
            </li>
        {% endif %}
    {% endfor %}


  </main>
{% endblock %}

myblog/templates/web/index.html
{% extends 'web/base_main.html' %}

{% block search %}
{{ super() }}

<div class="fenlei">
    <h2>文章分类</h2>
    {% for type in types %}
    <ul>
        <li><a href="{{ url_for('web.category',id=type.id)}}">{{ type.t_name }}</a></li>
    </ul>
    {% endfor %}
</div>
<div class="links">
    <h2>友情链接<a href="http://47.100.245.103/web/" target="_top">leejun</a></h2>
</div>
<div class="guanzhu">
<h2>关注我 么么哒</h2>
<ul>
    <img src="/static/web/images/wx.jpg">
</ul>
</div>
{% endblock %}

{% block content %}
    <main class="r_box">
        {{ error }}
            {% for article in articles %}

                {% if article.id % 10 == 0 %}
                    <li><i><a href="/"><img src="/static/web/images/10.jpg"></a></i>
                {% endif %}

                {% if article.id % 10 != 0 %}
                    <li><i><a href="/"><img src="/static/web/images/{{ article.id%10 }}.jpg"></a></i>
                {% endif%}

                <h3><a href="{{ url_for('web.info',id=article.id)}}">{{ article.title }}</a></h3>
                <p>{{ article.desc }}</p>

                    </li>
         {% endfor %}
        <div class="paging">
        {% if paginate.page%}
        <a>当前第{{ paginate.page }}页</a>
        {% endif %}

        {% if paginate.has_prev %}
            <a href="/web/index/?page={{ paginate.prev_num }}">上一页</a>
        {% endif %}

        {% if paginate.pages %}
            {% for i in range(1,paginate.pages+1) %}
                <a href="/web/index/?page={{ i }}"> {{ i }}</a>
            {% endfor %}
        {% endif %}

        {% if paginate.has_next %}
            <a href="/web/index/?page={{ paginate.next_num }}">下一页</a>
        {% endif %}
            <a href="/web/index/?page={{ paginate.pages }}">最后一页</a>

        </div>

    </main>
{% endblock %}

myblog/templates/web/info.html
{% extends 'web/base_main.html' %}

{% block search %}
    {{ super() }}
        <div class="fenlei">
            <h2>文章分类</h2>
            {% for type in types %}
            <ul>
                <li><a href="/">{{ type.t_name }}</a></li>
            </ul>
            {% endfor %}
        </div>
        <div class="links">
            <h2>友情链接</h2>
        </div>
        <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
            <img src="/static/web/images/wx.jpg">
        </ul>
        </div>
{% endblock %}

{% block content %}
  <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title">{{ article.title }}</h3>
        <div class="bloginfo">
          <ul>
            <li class="lmname"><a href="/">{{ article.t_name }}</a></li>
            <li class="timer">{{ article.create_time }}</li>
          </ul>
        </div>
        <div class="tags"><a href="" target="_blank">个人博客</a> &nbsp; <a href="" target="_blank">基础学习</a></div>
        <div class="news_about"><strong>简介</strong>每天工作回家后就能访问自己的网站，一边听着音乐，一边写写文章。</div>
        <div class="news_con">
          {{ article.content | safe }}
          &nbsp; </div>
      </div>
      <div class="share">
        <p class="diggit"><a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');"> 很赞哦！ </a>(<b id="diggnum"><script type="text/javascript" src="/e/public/ViewClick/?classid=2&id=20&down=5"></script>{{ article.id }}</b>)</p>
      </div>
      <div class="nextinfo">
        <p>上一篇：<a href="">{{ n_article.title }}</a></p>
        <p>下一篇：<a href="/news/life/"></a><a href="{{ url_for('web.index')}}">返回列表</a></p>
      </div>
      </div>
  </main>
{% endblock %}

myblog/templates/web/share.html
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<script src="/static/web/js/scrollReveal.js"></script>
</head>
<body>
<header class="header-navigation" id="header">
    <nav><div class="logo"><a href="{{ url_for('web.index') }}">郑晓卫个人博客</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
        <li><a href="{{ url_for('web.index') }}">网站首页</a></li>
        <li><a href="{{ url_for('web.share') }}">我的相册</a></li>
        <!--<li><a href="">我的日记</a></li>-->
        <!--<li><a href="">留言</a></li>-->
        <li><a href="{{url_for('web.content')}}">内容页</a></li>
        <li><a href="{{ url_for('web.about') }}">关于我</a></li>
        </ul>
    </nav>
</header>
<article>
        <div class="picbox">
            {% for i in range(1,14) %}

            <ul>
                <li data-scroll-reveal="enter bottom over 1s" ><i><img src="/static/web/images/{{ i }}.jpg"></i>
                </li>

            </ul>
            {% endfor %}
        </div>
    </article>

<script>
	if (!(/msie [6|7|8|9]/i.test(navigator.userAgent))){
		(function(){
			window.scrollReveal = new scrollReveal({reset: true});
		})();
	};
</script>
</body>
</html>